export {default as Landing} from './Landing'
export {default as HomeLayout} from './HomeLayout'
export {default as About} from './About'
export {default as Newsletter} from './Newsletter'
export {default as Error} from './Error'
export {default as BookingDetail} from './BookingDetail'
export {default as ExplorePlaces} from './ExplorePlaces'
export {default as ReviewPage} from './ReviewPage'